root: true
env:
  browser: true
  node: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
parserOptions:
  ecmaVersion: latest
settings:
  "next":
    "rootDir": "./web"
rules: {}
